Repository capstone-kw-jjiggle/rankit-be, pull requests merged in 2024-08, with the labels that each got.

#162 [refactor] 지금까지 진행했던 작업 관련하여 동기화 진행 -> 승준씨랑 회의하며 진행한 작업
  src/main/java/gitbal/backend/api/auth/dto/UserDto.java
  src/main/java/gitbal/backend/api/auth/service/AuthService.java
  src/main/java/gitbal/backend/api/info/service/RegionInfoService.java
  src/main/java/gitbal/backend/api/mainPage/controller/MainPageController.java
  src/main/java/gitbal/backend/api/mainPage/service/MainPageService.java
  src/main/java/gitbal/backend/api/regionPage/controller/RegionRankController.java
  src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
  src/main/java/gitbal/backend/api/schoolPage/controller/SchoolRankController.java
  src/main/java/gitbal/backend/api/userPage/controller/MyPageController.java
  src/main/java/gitbal/backend/api/userPage/controller/UserRankContorller.java
  src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
  src/main/java/gitbal/backend/api/userPage/service/UserRankService.java
  src/main/java/gitbal/backend/domain/onedaycommit/OneDayCommitRepository.java
  src/main/java/gitbal/backend/domain/onedaycommit/OneDayCommitService.java
  src/main/java/gitbal/backend/domain/onedaycommit/application/OneDayCommit.java
  src/main/java/gitbal/backend/domain/onedaycommit/application/repository/OneDayCommitRepository.java
  src/main/java/gitbal/backend/domain/onedaycommit/infra/OneDayCommitJpaEntity.java
  src/main/java/gitbal/backend/domain/onedaycommit/infra/OneDayCommitJpaRepository.java
  src/main/java/gitbal/backend/domain/onedaycommit/infra/OneDayCommitRepositoryImpl.java
  src/main/java/gitbal/backend/domain/refreshtoken/application/RefreshTokenService.java
  src/main/java/gitbal/backend/domain/refreshtoken/application/repository/RefreshTokenRepository.java
  src/main/java/gitbal/backend/domain/refreshtoken/infra/RefreshTokenJpaRepository.java
  src/main/java/gitbal/backend/domain/refreshtoken/infra/RefreshTokenRepositoryImpl.java
  src/main/java/gitbal/backend/domain/region/application/RegionContributorUpdater.java
  src/main/java/gitbal/backend/domain/region/application/RegionJoinUpdater.java
  src/main/java/gitbal/backend/domain/region/application/RegionRaceStatus.java
  src/main/java/gitbal/backend/domain/region/application/RegionScheduleUpdater.java
  src/main/java/gitbal/backend/domain/region/application/RegionService.java
  src/main/java/gitbal/backend/domain/region/application/repository/RegionRepository.java
  src/main/java/gitbal/backend/domain/region/infra/RegionJpaRepository.java
  src/main/java/gitbal/backend/domain/region/infra/RegionRepositoryImpl.java
  src/main/java/gitbal/backend/domain/school/SchoolContibutorUpdater.java
  src/main/java/gitbal/backend/domain/school/SchoolJoinUpdater.java
  src/main/java/gitbal/backend/domain/school/SchoolScheduleUpdater.java
  src/main/java/gitbal/backend/domain/school/SchoolService.java
  src/main/java/gitbal/backend/domain/user/User.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
  src/main/java/gitbal/backend/global/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/gitbal/backend/global/security/jwt/JwtTokenProvider.java
  src/main/java/gitbal/backend/global/util/ContributorUpdater.java
  src/main/java/gitbal/backend/global/util/JoinUpdater.java
  src/main/java/gitbal/backend/global/util/ScheduleUpdater.java
  src/main/java/gitbal/backend/schedule/SchedulingService.java
  src/main/java/gitbal/backend/schedule/userupdate/onedaycommit/UserOneDayCommitUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/score/UserScoreUpdaterImpl.java
  src/test/java/gitbal/backend/domain/onedaycommit/OneDayCommitJpaEntityServiceTest.java
  src/test/java/gitbal/backend/domain/refreshtoken/RefreshTokenServiceTest.java
  src/test/java/gitbal/backend/domain/region/RegionServiceTest.java
Labels: refactor

#166 Feature/#164 fix school region main
  src/main/java/gitbal/backend/api/mainPage/controller/MainPageController.java
  src/main/java/gitbal/backend/api/mainPage/dto/MainPageFirstRankResponseDto.java
  src/main/java/gitbal/backend/api/mainPage/service/MainPageService.java
  src/main/java/gitbal/backend/api/regionPage/controller/RegionRankController.java
  src/main/java/gitbal/backend/api/regionPage/dto/FirstRankRegionDto.java
  src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
  src/main/java/gitbal/backend/api/schoolPage/controller/SchoolRankController.java
  src/main/java/gitbal/backend/api/schoolPage/dto/FirstRankSchoolDto.java
  src/main/java/gitbal/backend/api/schoolPage/service/SchoolRankService.java
  src/main/java/gitbal/backend/domain/region/application/repository/RegionRepository.java
  src/main/java/gitbal/backend/domain/region/infra/RegionRepositoryImpl.java
  src/main/java/gitbal/backend/domain/school/SchoolRepository.java
  src/main/java/gitbal/backend/global/exception/MainPageFirstRankException.java
  src/main/java/gitbal/backend/global/handler/GlobalExceptionHandler.java
Labels: fix

#165 [fix] /api/v1/userRank/raced 삭제 작업 진행 : 모각코를 통하여 작업 현황 공유 및 리뷰 완료
  src/main/java/gitbal/backend/api/userPage/controller/MyPageController.java
  src/main/java/gitbal/backend/api/userPage/controller/UserRankContorller.java
  src/main/java/gitbal/backend/api/userPage/service/UserRankService.java
  src/main/java/gitbal/backend/domain/user/UserRaceStatus.java
  src/main/java/gitbal/backend/domain/user/UserRepository.java
  src/main/java/gitbal/backend/domain/user/UserService.java
  src/main/java/gitbal/backend/global/util/SurroundingRankStatus.java
  src/test/java/gitbal/backend/domain/user/UserServiceTest.java
Labels: fix

#167 [fix] userPage에 사용되어진 API( /api/v1/userRank/~~ ) 에 이뤄져야하는 응답 수정 및 이에 따른 부가 작업들을 수행하였습니다.
  src/main/java/gitbal/backend/api/userPage/controller/UserRankContorller.java
  src/main/java/gitbal/backend/api/userPage/dto/RegionRankDto.java
  src/main/java/gitbal/backend/api/userPage/dto/RegionRankRaceResponseDto.java
  src/main/java/gitbal/backend/api/userPage/dto/RegionRankResponseDto.java
  src/main/java/gitbal/backend/api/userPage/dto/SchoolRankDto.java
  src/main/java/gitbal/backend/api/userPage/dto/SchoolRankRaceResponseDto.java
  src/main/java/gitbal/backend/api/userPage/dto/SchoolRankResponseDto.java
  src/main/java/gitbal/backend/api/userPage/dto/UserRankMajorLanguageResponseDto.java
  src/main/java/gitbal/backend/api/userPage/dto/UserRankScoreResponseDto.java
  src/main/java/gitbal/backend/api/userPage/dto/UserRankingResponseDto.java
  src/main/java/gitbal/backend/api/userPage/service/UserRankService.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/LanguageResponseConverter.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageService.java
  src/main/java/gitbal/backend/domain/region/application/RegionRaceStatus.java
  src/main/java/gitbal/backend/domain/region/application/RegionService.java
  src/main/java/gitbal/backend/domain/school/SchoolRaceStatus.java
  src/main/java/gitbal/backend/domain/school/SchoolService.java
  src/main/java/gitbal/backend/domain/user/UserRaceStatus.java
  src/main/java/gitbal/backend/global/util/RaceStatus.java
  src/main/java/gitbal/backend/global/util/SurroundingRankStatus.java
  src/test/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageServiceTest.java
  src/test/java/gitbal/backend/domain/region/RegionServiceTest.java
  src/test/java/gitbal/backend/domain/school/SchoolServiceTest.java
  src/test/java/gitbal/backend/domain/user/UserServiceTest.java
Labels: fix

#170 Feature/#169 apply changes school region
  src/main/java/gitbal/backend/api/regionPage/controller/RegionRankController.java
  src/main/java/gitbal/backend/api/regionPage/dto/RegionListDto.java
  src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
  src/main/java/gitbal/backend/api/schoolPage/controller/SchoolRankController.java
  src/main/java/gitbal/backend/api/schoolPage/dto/SchoolListDto.java
  src/main/java/gitbal/backend/api/schoolPage/service/SchoolRankService.java
Labels: enhancement

#172 [feat] 방명록 관련 api 구현 (방명록이라는 네이밍을 추후 논의 후 변경 예정)
  build.gradle
  src/main/java/gitbal/backend/api/guestBookPage/controller/GuestBookPageController.java
  src/main/java/gitbal/backend/api/guestBookPage/dto/GuestBookResponseDto.java
  src/main/java/gitbal/backend/api/guestBookPage/dto/GuestBookWriteRequestDto.java
  src/main/java/gitbal/backend/api/guestBookPage/facade/GuestBookPageFacade.java
  src/main/java/gitbal/backend/domain/guestbook/GuestBook.java
  src/main/java/gitbal/backend/domain/guestbook/application/GuestBookService.java
  src/main/java/gitbal/backend/domain/guestbook/application/GuestBookServiceImpl.java
  src/main/java/gitbal/backend/domain/guestbook/infra/repository/GuestBookRepository.java
  src/main/java/gitbal/backend/domain/user/User.java
  src/main/java/gitbal/backend/domain/user/UserService.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
  src/test/java/gitbal/backend/domain/guestbook/application/GuestBookServiceSynarioTest.java
Labels: enhancement

#175 [fix] OneDayCommit 제거 작업 진행!
  src/main/java/gitbal/backend/api/auth/dto/UserDto.java
  src/main/java/gitbal/backend/api/auth/service/AuthService.java
  src/main/java/gitbal/backend/domain/onedaycommit/OneDayCommitService.java
  src/main/java/gitbal/backend/domain/onedaycommit/application/OneDayCommit.java
  src/main/java/gitbal/backend/domain/onedaycommit/application/repository/OneDayCommitRepository.java
  src/main/java/gitbal/backend/domain/onedaycommit/infra/OneDayCommitJpaEntity.java
  src/main/java/gitbal/backend/domain/onedaycommit/infra/OneDayCommitJpaRepository.java
  src/main/java/gitbal/backend/domain/onedaycommit/infra/OneDayCommitRepositoryImpl.java
  src/main/java/gitbal/backend/domain/user/User.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
  src/main/java/gitbal/backend/schedule/SchedulingService.java
  src/main/java/gitbal/backend/schedule/userupdate/onedaycommit/UserOneDayCommitUpdater.java
  src/main/java/gitbal/backend/schedule/userupdate/onedaycommit/UserOneDayCommitUpdaterImpl.java
  src/test/java/gitbal/backend/BackendApplicationTests.java
  src/test/java/gitbal/backend/domain/onedaycommit/OneDayCommitJpaEntityServiceTest.java
Labels: fix

#173 Feature/#171 friend suggestion
  src/main/java/gitbal/backend/api/auth/dto/UserDto.java
  src/main/java/gitbal/backend/api/auth/service/AuthService.java
  src/main/java/gitbal/backend/api/userPage/RandomFriendPicker.java
  src/main/java/gitbal/backend/api/userPage/controller/MyPageController.java
  src/main/java/gitbal/backend/api/userPage/dto/FriendSuggestDTO.java
  src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
  src/main/java/gitbal/backend/domain/majorlanguage/MajorLanguage.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageService.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageUpdater.java
  src/main/java/gitbal/backend/domain/majorlanguage/infra/MajorLanguageJpaEntity.java
  src/main/java/gitbal/backend/domain/majorlanguage/infra/MajorLanguageRepositoryImpl.java
  src/main/java/gitbal/backend/domain/user/User.java
  src/main/java/gitbal/backend/domain/user/UserService.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
  src/main/java/gitbal/backend/global/util/GithubDataService.java
  src/main/java/gitbal/backend/schedule/userupdate/majorLanguage/UserLanguagesUpdaterImpl.java
  src/test/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageServiceTest.java
Labels: enhancement

#178 Feature/#177 introduction
  src/main/java/gitbal/backend/api/auth/dto/UserDto.java
  src/main/java/gitbal/backend/api/auth/service/AuthService.java
  src/main/java/gitbal/backend/api/userPage/controller/MyPageController.java
  src/main/java/gitbal/backend/api/userPage/dto/FriendSuggestDto.java
  src/main/java/gitbal/backend/api/userPage/dto/IntroductionResponseDto.java
  src/main/java/gitbal/backend/api/userPage/dto/IntroductionupdateRequestDto.java
  src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
  src/main/java/gitbal/backend/domain/introduction/Introduction.java
  src/main/java/gitbal/backend/domain/introduction/application/repository/IntroductionRepository.java
  src/main/java/gitbal/backend/domain/introduction/infra/IntroductionJpaRepository.java
  src/main/java/gitbal/backend/domain/introduction/infra/IntroductionRepositoryImpl.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/repository/MajorLanguageRepository.java
  src/main/java/gitbal/backend/domain/user/User.java
  src/main/java/gitbal/backend/global/exception/NotUserPermissionException.java
  src/main/java/gitbal/backend/global/handler/GlobalExceptionHandler.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
Labels: enhancement

#179 [feat] 학교, 지역 클릭시 해당하는 도메인에 맞게 학생들을 랭킹 순서대로 보여주는 기능
  src/main/java/gitbal/backend/api/regionPage/controller/RegionRankController.java
  src/main/java/gitbal/backend/api/regionPage/dto/UserInfoByRegion.java
  src/main/java/gitbal/backend/api/regionPage/dto/UserPageListByRegionResponseDto.java
  src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
  src/main/java/gitbal/backend/api/schoolPage/controller/SchoolRankController.java
  src/main/java/gitbal/backend/api/schoolPage/dto/UserInfoBySchool.java
  src/main/java/gitbal/backend/api/schoolPage/dto/UserPageListBySchoolResponseDto.java
  src/main/java/gitbal/backend/api/schoolPage/service/SchoolRankService.java
  src/main/java/gitbal/backend/domain/user/UserRepository.java
  src/main/java/gitbal/backend/global/exception/RegionRankPageUserInfoByRegionException.java
  src/main/java/gitbal/backend/global/exception/SchoolRankPageUserInfoBySchoolException.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
Labels: enhancement
