Repository capstone-kw-jjiggle/rankit-be, pull requests merged in 2024-05, with the labels that each got.

#55 Feature/#50 api/v1/school rank/first school
  src/main/java/gitbal/backend/controller/RegionRankController.java
  src/main/java/gitbal/backend/controller/SchoolRankController.java
  src/main/java/gitbal/backend/entity/dto/FirstRankRegionDto.java
  src/main/java/gitbal/backend/entity/dto/FirstRankSchoolDto.java
  src/main/java/gitbal/backend/repository/RegionRepository.java
  src/main/java/gitbal/backend/repository/SchoolRepository.java
  src/main/java/gitbal/backend/service/RegionRankService.java
  src/main/java/gitbal/backend/service/SchoolRankService.java
Labels: enhancement

#56 [feat] #51 - regionRank/firstRegion
  src/main/java/gitbal/backend/controller/RegionRankController.java
  src/main/java/gitbal/backend/entity/dto/FirstRankRegionDto.java
  src/main/java/gitbal/backend/repository/RegionRepository.java
  src/main/java/gitbal/backend/service/RegionRankService.java
Labels: enhancement

#57 [feat] /api/v1/mainPage/users 개발
  src/main/java/gitbal/backend/controller/MainPageController.java
  src/main/java/gitbal/backend/domain/PageCalculator.java
  src/main/java/gitbal/backend/entity/Grade.java
  src/main/java/gitbal/backend/entity/User.java
  src/main/java/gitbal/backend/entity/dto/MainPageUserDto.java
  src/main/java/gitbal/backend/entity/dto/MainPageUserResponseDto.java
  src/main/java/gitbal/backend/entity/dto/PageInfoDto.java
  src/main/java/gitbal/backend/exception/GlobalExceptionHandler.java
  src/main/java/gitbal/backend/exception/MainPageException.java
  src/main/java/gitbal/backend/mock/MockDataGenerator.java
  src/main/java/gitbal/backend/service/LoginService.java
  src/main/java/gitbal/backend/service/MainPageService.java
Labels: enhancement

#59 [feat] /api/v1/mainPage/search 개발
  src/main/java/gitbal/backend/controller/MainPageController.java
  src/main/java/gitbal/backend/domain/PageCalculator.java
  src/main/java/gitbal/backend/repository/UserRepository.java
  src/main/java/gitbal/backend/service/MainPageService.java
Labels: enhancement

#61 [feat] #53 - /api/v1/mainPage/firstRank 기능 구현
  src/main/java/gitbal/backend/controller/MainPageController.java
  src/main/java/gitbal/backend/entity/dto/MainPageFirstRankResponseDto.java
  src/main/java/gitbal/backend/service/MainPageService.java
Labels: enhancement

#62 [chore] #53 - swagger 관련 문서 mainPageController에 작성
  src/main/java/gitbal/backend/controller/MainPageController.java
Labels: documentation

#63 [feat] #60 - mainPageException 처리 관련하여서 수정
  src/main/java/gitbal/backend/controller/MainPageController.java
  src/main/java/gitbal/backend/exception/GlobalExceptionHandler.java
  src/main/java/gitbal/backend/exception/MainPageException.java
  src/main/java/gitbal/backend/exception/MainPageFirstRankException.java
  src/main/java/gitbal/backend/exception/NotFoundUserException.java
  src/main/java/gitbal/backend/exception/WrongPageNumberException.java
  src/main/java/gitbal/backend/service/MainPageService.java
Labels: enhancement

#71 [feat] #65 - /api/v1/schoolRank/mySchool
  src/main/java/gitbal/backend/config/SecurityConfig.java
  src/main/java/gitbal/backend/controller/SchoolRankController.java
  src/main/java/gitbal/backend/entity/dto/MySchoolInfoResponseDto.java
  src/main/java/gitbal/backend/exception/GlobalExceptionHandler.java
  src/main/java/gitbal/backend/exception/NotLoginedException.java
  src/main/java/gitbal/backend/repository/SchoolRepository.java
  src/main/java/gitbal/backend/service/SchoolRankService.java
Labels: enhancement

#72 [chore] #70 - swagger에 jwt 토큰 넣어서 인증한 상태로 진행할 수 있게 추가
  src/main/java/gitbal/backend/config/SwaggerConfig.java
Labels: documentation

#81 [feat] #79 - /api/v1/schoolRank/search 구현 진행
  src/main/java/gitbal/backend/controller/SchoolRankController.java
  src/main/java/gitbal/backend/exception/GlobalExceptionHandler.java
  src/main/java/gitbal/backend/exception/NotFoundSchoolException.java
  src/main/java/gitbal/backend/repository/SchoolRepository.java
  src/main/java/gitbal/backend/service/SchoolRankService.java
Labels: enhancement

#83 Feature/#82 add custom exception response entity
  src/main/java/gitbal/backend/controller/CommonController.java
  src/main/java/gitbal/backend/controller/MyPageController.java
  src/main/java/gitbal/backend/controller/RegionRankController.java
  src/main/java/gitbal/backend/controller/SchoolRankController.java
  src/main/java/gitbal/backend/controller/UnivController.java
  src/main/java/gitbal/backend/exception/GlobalExceptionHandler.java
  src/main/java/gitbal/backend/exception/NotFoundRegionException.java
  src/main/java/gitbal/backend/exception/PageOutOfRangeException.java
  src/main/java/gitbal/backend/service/MyPageService.java
  src/main/java/gitbal/backend/service/RegionRankService.java
  src/main/java/gitbal/backend/service/SchoolRankService.java
  src/main/java/gitbal/backend/service/UserInfoService.java
Labels: enhancement

#84 [fix] Spring Security 관련 refreshToken 수정 작업 진행
  src/main/java/gitbal/backend/entity/RefreshToken.java
  src/main/java/gitbal/backend/repository/RefreshTokenRepository.java
  src/main/java/gitbal/backend/repository/TokenInfoRepository.java
  src/main/java/gitbal/backend/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/gitbal/backend/security/jwt/JwtAuthenticationFilter.java
  src/main/java/gitbal/backend/security/jwt/JwtTokenProvider.java
Labels: enhancement

#85 [chore] #74 - 이름 수정 -> userId보다는 닉네임인거 같아서 변경!
  src/main/java/gitbal/backend/entity/RefreshToken.java
  src/main/java/gitbal/backend/repository/RefreshTokenRepository.java
  src/main/java/gitbal/backend/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/gitbal/backend/security/jwt/JwtTokenProvider.java
Labels: chore

#89 [feat] #88 - cors설정 진행
  src/main/java/gitbal/backend/config/SecurityConfig.java
  src/main/java/gitbal/backend/security/OAuth2AuthenticationSuccessHandler.java
Labels: enhancement

#96 [fix] loginAPI 관련 이전 방식과 다르게 고치는 작업 진행
  src/main/java/gitbal/backend/api/auth/controller/AuthController.java
  src/main/java/gitbal/backend/api/auth/controller/LoginController.java
  src/main/java/gitbal/backend/api/auth/service/AuthService.java
  src/main/java/gitbal/backend/api/auth/service/LoginService.java
  src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
  src/main/java/gitbal/backend/global/config/SecurityConfig.java
  src/main/java/gitbal/backend/global/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/gitbal/backend/global/security/jwt/JwtTokenProvider.java
  src/main/java/gitbal/backend/global/util/AuthenticationChecker.java
Labels: fix

#100 [refactor] #90 - MyPage 관련 코드 리팩토링
  src/main/java/gitbal/backend/api/schoolPage/service/SchoolRankService.java
  src/main/java/gitbal/backend/api/userPage/controller/MyPageController.java
  src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
  src/main/java/gitbal/backend/domain/region/RegionService.java
  src/main/java/gitbal/backend/domain/school/SchoolService.java
  src/main/java/gitbal/backend/domain/user/UserService.java
Labels: refactor

#101 [feat] #97 /api/v1/auth/logout 구현
  src/main/java/gitbal/backend/api/auth/controller/AuthController.java
  src/main/java/gitbal/backend/api/auth/service/AuthService.java
  src/main/java/gitbal/backend/domain/refreshtoken/RefreshTokenRepository.java
  src/main/java/gitbal/backend/domain/refreshtoken/RefreshTokenService.java
  src/main/java/gitbal/backend/global/config/SecurityConfig.java
  src/main/java/gitbal/backend/global/exception/LogoutException.java
  src/main/java/gitbal/backend/global/exception/NoTokenException.java
  src/main/java/gitbal/backend/global/exception/NotFoundRefreshTokenException.java
  src/main/java/gitbal/backend/global/handler/GlobalExceptionHandler.java
  src/main/java/gitbal/backend/global/security/CustomLogoutHandler.java
  src/main/java/gitbal/backend/global/security/CustomLogoutSuccessHandler.java
  src/main/java/gitbal/backend/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/gitbal/backend/global/security/jwt/JwtTokenProvider.java
  src/main/java/gitbal/backend/global/security/jwt/JwtUtils.java
Labels: enhancement

#103 [fix] #102 0526 대면 회의 진행하면서 수정하거나, 기능 추가한 내용들 추가
  src/main/java/gitbal/backend/api/auth/controller/AuthController.java
  src/main/java/gitbal/backend/api/auth/dto/JoinRequestDto.java
  src/main/java/gitbal/backend/api/auth/service/AuthService.java
  src/main/java/gitbal/backend/api/auth/service/LoginService.java
  src/main/java/gitbal/backend/api/auth/service/UserInfoService.java
  src/main/java/gitbal/backend/api/info/controller/InfoController.java
  src/main/java/gitbal/backend/api/info/service/InfoService.java
  src/main/java/gitbal/backend/api/info/service/RegionInfoService.java
  src/main/java/gitbal/backend/api/info/service/SchoolInfoService.java
  src/main/java/gitbal/backend/api/userPage/controller/MyPageController.java
  src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
  src/main/java/gitbal/backend/domain/user/UserService.java
  src/main/java/gitbal/backend/global/config/SecurityConfig.java
  src/main/java/gitbal/backend/global/security/jwt/JwtAuthenticationFilter.java
Labels: enhancement

#105 [hotfix] #102 - 응답 제대로 가지 않았던 코드 수정
  src/main/java/gitbal/backend/api/info/controller/InfoController.java
  src/main/java/gitbal/backend/api/info/service/InfoService.java
  src/main/java/gitbal/backend/api/info/service/RegionInfoService.java
  src/main/java/gitbal/backend/api/info/service/SchoolInfoService.java
Labels: fix

#106 [feat] #104 - school, user 등급 계산 후 적용
  README.md
  src/main/java/gitbal/backend/api/auth/service/AuthService.java
  src/main/java/gitbal/backend/domain/school/School.java
  src/main/java/gitbal/backend/domain/user/User.java
  src/main/java/gitbal/backend/global/constant/Grade.java
  src/main/java/gitbal/backend/global/constant/SchoolGrade.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
Labels: enhancement

#114 [feat] fe 요청사항으로 재로그인 시 서비스에 등록여부 queryParam을 통해 알려주기
  src/main/java/gitbal/backend/api/auth/service/LoginService.java
Labels: enhancement
