Repository capstone-kw-jjiggle/rankit-be, pull requests merged in 2024-10, with the labels that each got.

#196 [feat] api part 1 검토 작업 진행
  src/main/java/gitbal/backend/api/auth/controller/AuthController.java
  src/main/java/gitbal/backend/api/auth/dto/GitbalApiDto.java
  src/main/java/gitbal/backend/api/auth/service/AuthService.java
  src/main/java/gitbal/backend/api/auth/service/LoginService.java
  src/main/java/gitbal/backend/api/mainPage/controller/MainPageController.java
  src/main/java/gitbal/backend/api/mainPage/dto/MainPageUserDto.java
  src/main/java/gitbal/backend/api/mainPage/service/MainPageService.java
  src/main/java/gitbal/backend/api/schoolPage/service/SchoolRankService.java
  src/main/java/gitbal/backend/api/userPage/controller/UserRankContorller.java
  src/main/java/gitbal/backend/api/userPage/dto/UserRankExpResponseDto.java
  src/main/java/gitbal/backend/api/userPage/service/UserRankService.java
  src/main/java/gitbal/backend/domain/user/UserRepository.java
  src/main/java/gitbal/backend/domain/user/UserService.java
  src/main/java/gitbal/backend/global/constant/Grade.java
  src/main/java/gitbal/backend/global/exception/UnivCertStartException.java
  src/main/java/gitbal/backend/global/exception/UserHasNoMajorLanguageException.java
  src/main/java/gitbal/backend/global/exception/UserHasNoRegionException.java
  src/main/java/gitbal/backend/global/exception/UserHasNoSchoolException.java
  src/main/java/gitbal/backend/global/exception/UserRankingException.java
  src/main/java/gitbal/backend/global/handler/GlobalExceptionHandler.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
  src/main/java/gitbal/backend/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/gitbal/backend/global/security/jwt/JwtTokenProvider.java
Labels: enhancement, refactor, fix

#197 Feature/#191 test2
  src/main/java/gitbal/backend/api/guestBookPage/controller/GuestBookPageController.java
  src/main/java/gitbal/backend/api/guestBookPage/facade/GuestBookPageFacade.java
  src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
  src/main/java/gitbal/backend/api/userPage/dto/IntroductionupdateRequestDto.java
  src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
  src/main/java/gitbal/backend/domain/guestbook/application/GuestBookService.java
  src/main/java/gitbal/backend/domain/guestbook/application/GuestBookServiceImpl.java
  src/main/java/gitbal/backend/global/config/SecurityConfig.java
  src/main/java/gitbal/backend/global/handler/GlobalExceptionHandler.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
  src/main/java/gitbal/backend/global/security/jwt/JwtAuthenticationFilter.java
  src/test/java/gitbal/backend/domain/guestbook/application/GuestBookServiceSynarioTest.java
Labels: enhancement

#198 [fix] #190 - 경험치 계산 과정중 PURPLE 등급일때 났던 오류 해결
  src/main/java/gitbal/backend/domain/user/UserService.java
  src/main/java/gitbal/backend/global/constant/Grade.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
Labels: fix

#200 Feat/#199 swagger fix
  src/main/java/gitbal/backend/api/auth/controller/AuthController.java
  src/main/java/gitbal/backend/api/auth/controller/LoginController.java
  src/main/java/gitbal/backend/api/badge/controller/BadgeController.java
  src/main/java/gitbal/backend/api/guestBookPage/controller/GuestBookPageController.java
  src/main/java/gitbal/backend/api/info/controller/InfoController.java
  src/main/java/gitbal/backend/api/mainPage/controller/MainPageController.java
  src/main/java/gitbal/backend/api/regionPage/controller/RegionRankController.java
  src/main/java/gitbal/backend/api/schoolPage/controller/SchoolRankController.java
  src/main/java/gitbal/backend/api/univcert/controller/UnivController.java
  src/main/java/gitbal/backend/api/userPage/controller/MyPageController.java
  src/main/java/gitbal/backend/api/userPage/controller/UserRankContorller.java
Labels: fix

#203 [feat] #201 - 필요없었던 컬럼 제거, 스케쥴링 필요없던 로직 제거 및 비동기로 스레드 나눠서 스케쥴링 작업 수행하도록 변경, majorLanguage Table 삭제 작업 진행
  src/main/java/gitbal/backend/api/auth/dto/UserDto.java
  src/main/java/gitbal/backend/api/auth/service/AuthService.java
  src/main/java/gitbal/backend/api/badge/service/BadgeServiceImpl.java
  src/main/java/gitbal/backend/api/regionPage/dto/MyRegionInfoResponseDto.java
  src/main/java/gitbal/backend/api/schoolPage/dto/MySchoolInfoResponseDto.java
  src/main/java/gitbal/backend/api/schoolPage/dto/SchoolListDto.java
  src/main/java/gitbal/backend/api/userPage/RandomFriendPicker.java
  src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
  src/main/java/gitbal/backend/domain/majorlanguage/MajorLanguageDto.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageJsonParser.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageService.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageUpdater.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/repository/MajorLanguageRepository.java
  src/main/java/gitbal/backend/domain/majorlanguage/infra/MajorLanguageJpaEntity.java
  src/main/java/gitbal/backend/domain/majorlanguage/infra/MajorLanguageJpaRepository.java
  src/main/java/gitbal/backend/domain/majorlanguage/infra/MajorLanguageRepositoryImpl.java
  src/main/java/gitbal/backend/domain/region/Region.java
  src/main/java/gitbal/backend/domain/region/application/RegionJoinUpdater.java
  src/main/java/gitbal/backend/domain/region/application/RegionScheduleUpdater.java
  src/main/java/gitbal/backend/domain/region/application/RegionService.java
  src/main/java/gitbal/backend/domain/school/School.java
  src/main/java/gitbal/backend/domain/school/SchoolJoinUpdater.java
  src/main/java/gitbal/backend/domain/school/SchoolScheduleUpdater.java
  src/main/java/gitbal/backend/domain/school/SchoolService.java
  src/main/java/gitbal/backend/domain/user/User.java
  src/main/java/gitbal/backend/domain/user/UserRepository.java
  src/main/java/gitbal/backend/domain/user/UserService.java
  src/main/java/gitbal/backend/global/config/ScheduleConfig.java
  src/main/java/gitbal/backend/global/constant/SchoolGrade.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
  src/main/java/gitbal/backend/global/util/ContributorUpdater.java
  src/main/java/gitbal/backend/schedule/SchedulingService.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolGrade/SchoolGradeUpdater.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolGrade/SchoolGradeUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolPrevDayScore/SchoolPrevDayScoreUpdater.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolPrevDayScore/SchoolPrevDayScoreUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/majorLanguage/UserLanguagesUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/score/UserScoreUpdaterImpl.java
  src/main/resources/data.sql
  src/test/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageServiceTest.java
Labels: enhancement, refactor, fix

#208 Feature/#207 notloginedfriendsuggest
  src/main/java/gitbal/backend/api/userPage/RandomFriendPicker.java
  src/main/java/gitbal/backend/api/userPage/controller/MyPageController.java
  src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
  src/main/java/gitbal/backend/domain/user/UserService.java
  src/main/java/gitbal/backend/global/config/SecurityConfig.java
Labels: enhancement

#212 [fix] #209 - apiIssue관련 정리 네이밍 관련 정리
  src/main/java/gitbal/backend/api/auth/dto/UserInfoDto.java
  src/main/java/gitbal/backend/api/mainPage/dto/MainPageUserDto.java
  src/main/java/gitbal/backend/api/mainPage/service/MainPageService.java
  src/main/java/gitbal/backend/api/regionPage/dto/RegionListDto.java
  src/main/java/gitbal/backend/api/regionPage/dto/UserInfoByRegion.java
  src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
  src/main/java/gitbal/backend/api/schoolPage/dto/UserInfoBySchool.java
  src/main/java/gitbal/backend/api/schoolPage/service/SchoolRankService.java
  src/main/java/gitbal/backend/api/userPage/dto/FriendSuggestDto.java
Labels: fix

#213 [feat] #210 - 자기소개에 제목 추가
  src/main/java/gitbal/backend/api/userPage/dto/IntroductionResponseDto.java
  src/main/java/gitbal/backend/api/userPage/dto/IntroductionupdateRequestDto.java
  src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
  src/main/java/gitbal/backend/domain/introduction/Introduction.java
  src/main/java/gitbal/backend/domain/introduction/infra/IntroductionRepositoryImpl.java
Labels: enhancement

#214 [feat] 유저당 페이지 관련하여 api 제작(/api/v1/userInfo?username=~~~) 및 MyPage api 명칭 변경 작업 진행
  src/main/java/gitbal/backend/api/userPage/controller/UserPageController.java
  src/main/java/gitbal/backend/api/userPage/controller/UserRankContorller.java
  src/main/java/gitbal/backend/api/userPage/dto/UserPageUserInfoResponseDto.java
  src/main/java/gitbal/backend/api/userPage/service/UserPageService.java
  src/main/java/gitbal/backend/domain/user/UserService.java
Labels: enhancement, fix

#216 [fix] #215 - shedLock 을 이용하여 서버 이중화시 스케쥴링 로직 중복으로 실행되지 않을 수 있도록 구현
  build.gradle
  src/main/java/gitbal/backend/BackendApplication.java
  src/main/java/gitbal/backend/schedule/SchedulingService.java
  src/main/java/gitbal/backend/schedule/config/SchedulerLockConfig.java
  src/main/resources/data.sql
Labels: enhancement, fix

#218 [feat] User Update하는 과정속에서 일어났던 문제들
  src/main/java/gitbal/backend/api/auth/service/LoginService.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageService.java
  src/main/java/gitbal/backend/domain/user/UserRepository.java
  src/main/java/gitbal/backend/domain/user/UserService.java
  src/main/java/gitbal/backend/global/config/ScheduleConfig.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
  src/main/java/gitbal/backend/global/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/gitbal/backend/schedule/SchedulingService.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolRank/SchoolRankUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/majorLanguage/UserLanguagesUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/score/UserScoreUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/userGrade/UserGradeUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/userRank/UserRankUpdaterImpl.java
Labels: enhancement, fix
