Repository capstone-kw-jjiggle/rankit-be, pull requests merged in 2024-06, with the labels that each got.

#118 [fix] 배포 작업 진행중에 관련하여서 오류가 발생해서 오류 관련 처리 진행함.
  src/main/java/gitbal/backend/api/auth/controller/AuthController.java
  src/main/java/gitbal/backend/api/auth/dto/UserInfoDto.java
  src/main/java/gitbal/backend/api/auth/service/LoginService.java
  src/main/java/gitbal/backend/api/auth/service/UserAuthInfoService.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
  src/main/java/gitbal/backend/global/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/gitbal/backend/schedule/userupdate/onedaycommit/UserOneDayCommitUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/score/UserScoreUpdaterImpl.java
Labels: fix

#116 [feat] deploy를 위한 배포전 세팅 진행
  .gitignore
  Dockerfile
  database/conf/mysql.cnf
  docker-compose-local.yml
  docker-compose.yml
  src/main/java/gitbal/backend/api/auth/controller/AuthController.java
  src/main/java/gitbal/backend/api/auth/dto/UserInfoDto.java
  src/main/java/gitbal/backend/api/auth/service/LoginService.java
  src/main/java/gitbal/backend/api/auth/service/UserAuthInfoService.java
  src/main/java/gitbal/backend/global/healthcheck/HealthCheckController.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
  src/main/java/gitbal/backend/global/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/gitbal/backend/schedule/userupdate/onedaycommit/UserOneDayCommitUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/score/UserScoreUpdaterImpl.java
  src/main/resources/application-db.yml
  src/main/resources/application-jwt.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-token.yml
  src/main/resources/application-univ.yml
  src/main/resources/application.yml
Labels: enhancement

#119 [feat] #99 - swagger 요청에 배포에 요청을 보낼 수 있도록 url 추가
  src/main/java/gitbal/backend/BackendApplication.java
Labels: enhancement

#122 [fix] #121 - fe요청에 따른 검색시에 유저나 학교가 아무것도 없을 경우 빈 리스트로 전달, search api를 해당 컨트롤러의 list 불러오는 api에 통합
  src/main/java/gitbal/backend/api/mainPage/controller/MainPageController.java
  src/main/java/gitbal/backend/api/mainPage/service/MainPageService.java
  src/main/java/gitbal/backend/api/schoolPage/controller/SchoolRankController.java
  src/main/java/gitbal/backend/api/schoolPage/dto/SchoolListPageResponseDto.java
  src/main/java/gitbal/backend/api/schoolPage/service/SchoolRankService.java
Labels: fix

#115 Feature/#90 refactor univcert
  src/main/java/gitbal/backend/api/univcert/controller/UnivController.java
  src/main/java/gitbal/backend/api/univcert/dto/UnivCertCodeDto.java
  src/main/java/gitbal/backend/api/univcert/dto/UnivCertResponseDto.java
  src/main/java/gitbal/backend/api/univcert/dto/UnivCertStartDto.java
  src/main/java/gitbal/backend/api/univcert/service/UnivService.java
  src/main/java/gitbal/backend/global/exception/UnivCertCodeException.java
  src/main/java/gitbal/backend/global/exception/UnivCertStartException.java
  src/main/java/gitbal/backend/global/handler/GlobalExceptionHandler.java
  src/main/java/gitbal/backend/schedule/userupdate/userRank/RankUpdater.java
  src/main/java/gitbal/backend/schedule/userupdate/userRank/RankUpdaterImpl.java
Labels: refactor

#126 [fix] fe요청 사항에 따른 regionRank 수정작업 진행
  src/main/java/gitbal/backend/api/regionPage/dto/RegionListDto.java
  src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
Labels: fix

#130 [feat] - user가 로그인시에 profileImg가 바뀐 경우가 있어 oauth2Login시 업데이트 진행
  src/main/java/gitbal/backend/api/auth/controller/LoginController.java
  src/main/java/gitbal/backend/domain/user/User.java
  src/main/java/gitbal/backend/domain/user/UserService.java
  src/main/java/gitbal/backend/global/security/OAuth2AuthenticationSuccessHandler.java
Labels: enhancement

#131 [feat] userInfo 응답에 추가로 grade 추가, imageName 오타 -> imgUrl 로 수정
  src/main/java/gitbal/backend/api/auth/dto/UserInfoDto.java
Labels: enhancement

#133 [fix] - 잘못 응답이 갔던 myRegionRank 관련한 수정작업
  src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
  src/main/java/gitbal/backend/domain/region/RegionRepository.java
  src/main/java/gitbal/backend/domain/school/SchoolRepository.java
Labels: fix

#134 Feature/#120 scheuling grade update
  README.md
  src/main/java/gitbal/backend/domain/school/SchoolService.java
  src/main/java/gitbal/backend/domain/user/UserService.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
  src/main/java/gitbal/backend/schedule/SchedulingService.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolGrade/SchoolGradeUpdater.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolGrade/SchoolGradeUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolRank/SchoolRankUpdater.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolRank/SchoolRankUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/userGrade/UserGradeUpdater.java
  src/main/java/gitbal/backend/schedule/userupdate/userGrade/UserGradeUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/userRank/UserRankUpdater.java
  src/main/java/gitbal/backend/schedule/userupdate/userRank/UserRankUpdaterImpl.java
Labels: enhancement

#138 Feature/#127 changed score (학교의 전날대비 상승 점수 업데이트)
  src/main/java/gitbal/backend/domain/school/School.java
  src/main/java/gitbal/backend/domain/school/SchoolService.java
  src/main/java/gitbal/backend/schedule/SchedulingService.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolGrade/SchoolGradeUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolPrevDayScore/SchoolPrevDayScoreUpdater.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolPrevDayScore/SchoolPrevDayScoreUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolRank/SchoolRankUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/score/UserScoreUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/userGrade/UserGradeUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/userRank/UserRankUpdaterImpl.java
Labels: enhancement

#139 develop 브랜치에 #134 PR내용 merge
  src/main/java/gitbal/backend/domain/school/School.java
  src/main/java/gitbal/backend/domain/school/SchoolService.java
  src/main/java/gitbal/backend/schedule/SchedulingService.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolGrade/SchoolGradeUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolPrevDayScore/SchoolPrevDayScoreUpdater.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolPrevDayScore/SchoolPrevDayScoreUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/schoolupdate/schoolRank/SchoolRankUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/score/UserScoreUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/userGrade/UserGradeUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/userRank/UserRankUpdaterImpl.java
Labels: enhancement

#137 [feat] 학교, 지역이 등록되지 않은 경우에 대한 임시 처리작업 진행 -> 이후에 FE와 논의 후 응답 변경해야하지만 임시적으로 개발 진행
  src/main/java/gitbal/backend/api/auth/dto/UserInfoDto.java
  src/main/java/gitbal/backend/api/auth/service/UserAuthInfoService.java
  src/main/java/gitbal/backend/api/regionPage/dto/MyRegionInfoResponseDto.java
  src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
  src/main/java/gitbal/backend/api/schoolPage/dto/MySchoolInfoResponseDto.java
  src/main/java/gitbal/backend/api/userPage/service/UserRankService.java
  src/main/java/gitbal/backend/domain/user/UserRegionSchoolNameDto.java
  src/main/java/gitbal/backend/domain/user/UserService.java
Labels: enhancement

#141 Feature/#140 cicd
  .github/workflows/gradle.yml
  Dockerfile
  docker-compose.yml
  src/main/java/gitbal/backend/api/auth/dto/UserInfoDto.java
  src/main/java/gitbal/backend/api/auth/service/UserAuthInfoService.java
  src/main/java/gitbal/backend/api/regionPage/dto/MyRegionInfoResponseDto.java
  src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
  src/main/java/gitbal/backend/api/schoolPage/dto/MySchoolInfoResponseDto.java
  src/main/java/gitbal/backend/api/userPage/service/UserRankService.java
  src/main/java/gitbal/backend/domain/user/UserRegionSchoolNameDto.java
  src/main/java/gitbal/backend/domain/user/UserService.java
Labels: enhancement

#143 [feat] redirect url 변경작업 및 기타 환경변수 처리 진행
  .gitignore
  docker-compose.yml
  src/main/java/gitbal/backend/global/security/OAuth2AuthenticationSuccessHandler.java
  src/main/java/gitbal/backend/global/security/jwt/JwtTokenProvider.java
  src/main/resources/application-prod.yml
Labels: enhancement

#145 [feat] #144 - 학교 인증 처리할때 인증 성공했을 경우 인증 리스트 초기화 하여 이후 회원탈퇴에도 문제 없게 진행
  src/main/java/gitbal/backend/api/univcert/service/UnivService.java
Labels: enhancement

#147 [feat] #144 - mockData에서 khyojun 제거하고 학생 인증 테스트 진행
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
  src/main/java/gitbal/backend/schedule/userupdate/UserSetup.java
Labels: enhancement

#155 #152 내용 develop 에서 main으로 옮기기
  .github/workflows/action.yml
  docker-compose.yml
  src/main/java/gitbal/backend/global/healthcheck/HealthCheckController.java
Labels: enhancement

#156 [hotfix] #152 - 볼륨 선언 관련 수정
  docker-compose.yml
Labels: enhancement

#157 [hotfix] 스크립트에 맞추기 위해 container이름 지정해서 진행하기
  docker-compose.yml
Labels: fix

#158 [hotfix] 학교, 지역 관련 중복 삽입으로 인한 쿼리 수정 작업 진행
  src/main/java/gitbal/backend/domain/region/Region.java
  src/main/java/gitbal/backend/domain/school/School.java
  src/main/resources/data.sql
Labels: fix

#159 [hotfix] 중복문제 해결을 위하여 쿼리 수정하여 식별자와 함께 ignore 여부 확인하도록 진행
  src/main/resources/data.sql
Labels: fix

#148 Feature/#127 changed score
  src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
  src/main/java/gitbal/backend/domain/region/Region.java
  src/main/java/gitbal/backend/domain/region/RegionService.java
  src/main/java/gitbal/backend/domain/school/School.java
  src/main/java/gitbal/backend/schedule/SchedulingService.java
  src/main/java/gitbal/backend/schedule/regionupdate/regionPrevDayScore/RegionPrevDayScoreUpdater.java
  src/main/java/gitbal/backend/schedule/regionupdate/regionPrevDayScore/RegionPrevDayScoreUpdaterImpl.java
  src/main/java/gitbal/backend/schedule/userupdate/score/UserScoreUpdaterImpl.java
Labels: enhancement

#161 [test] #154 리팩토링 작업중 #160 일부 도메인 테스트 코드 작성 관련하여 미리 develop브랜치에 적용시키려고 합니다.
  src/main/java/gitbal/backend/api/auth/dto/UserDto.java
  src/main/java/gitbal/backend/api/auth/service/AuthService.java
  src/main/java/gitbal/backend/api/schoolPage/service/SchoolRankService.java
  src/main/java/gitbal/backend/api/userPage/service/UserRankService.java
  src/main/java/gitbal/backend/domain/majorlanguage/MajorLanguage.java
  src/main/java/gitbal/backend/domain/majorlanguage/MajorLanguageDto.java
  src/main/java/gitbal/backend/domain/majorlanguage/MajorLanguageRepository.java
  src/main/java/gitbal/backend/domain/majorlanguage/MajorLanguageService.java
  src/main/java/gitbal/backend/domain/majorlanguage/MajorLanguageUpdater.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/LanguageResponseConverter.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageJsonParser.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageService.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageUpdater.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/TopLanguageService.java
  src/main/java/gitbal/backend/domain/majorlanguage/application/repository/MajorLanguageRepository.java
  src/main/java/gitbal/backend/domain/majorlanguage/infra/MajorLanguageJpaEntity.java
  src/main/java/gitbal/backend/domain/majorlanguage/infra/MajorLanguageJpaRepository.java
  src/main/java/gitbal/backend/domain/majorlanguage/infra/MajorLanguageRepositoryImpl.java
  src/main/java/gitbal/backend/domain/onedaycommit/OneDayCommit.java
  src/main/java/gitbal/backend/domain/onedaycommit/OneDayCommitRepository.java
  src/main/java/gitbal/backend/domain/region/Region.java
  src/main/java/gitbal/backend/domain/school/School.java
  src/main/java/gitbal/backend/domain/school/SchoolService.java
  src/main/java/gitbal/backend/domain/user/User.java
  src/main/java/gitbal/backend/domain/user/UserService.java
  src/main/java/gitbal/backend/global/BaseTimeEntity.java
  src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
  src/main/java/gitbal/backend/global/util/GithubDataService.java
  src/main/java/gitbal/backend/schedule/SchedulingService.java
  src/main/java/gitbal/backend/schedule/userupdate/majorLanguage/UserLanguagesUpdaterImpl.java
  src/test/java/gitbal/backend/domain/majorlanguage/application/MajorLanguageServiceTest.java
  src/test/java/gitbal/backend/domain/onedaycommit/OneDayCommitServiceTest.java
  src/test/java/gitbal/backend/domain/refreshtoken/RefreshTokenServiceTest.java
  src/test/java/gitbal/backend/domain/region/RegionServiceTest.java
  src/test/java/gitbal/backend/domain/school/SchoolServiceTest.java
  src/test/java/gitbal/backend/domain/user/UserServiceTest.java
Labels: enhancement
